export const RECEIVE_RMS = 'RECEIVE_RMS';
export const SELECT_RMS = 'SELECT_RMS';
export const RECEIVE_METRICS = 'RECEIVE_METRICS';
export const RECEIVE_MATCH_JOB = 'RECEIVE_MATCH_JOB';
export const RECEIVE_CONFIGURATIONS = 'RECEIVE_CONFIGURATIONS';
export const RECEIVE_RECORD_SET = 'RECEIVE_RECORD_SET';
export const SELECT_RECORD_SET = 'SELECT_RECORD_SET';
